cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

my__shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', )),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', )),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from .views import order_create, admin_order_pdf

app_name = 'orders'


urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Mini shop</title>

  <!-- Bootstrap core CSS -->
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

  <!-- Custom styles for this template -->


</head>

<style>
  body {
  padding-top: 56px;
  background-color:#ffffff;
  }
</style>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">Tool Rental</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
           
          <li class="nav-item">
            <a class="nav-link" href="#">about us<span class="badge badge-pill badge-danger"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Delivery methods<span class="badge badge-pill badge-danger"></span></a>
          </li>
           
          <li class="nav-item">
            <a class="nav-link" href="#">watsapp<span class="badge badge-pill badge-danger"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">telegram<span class="badge badge-pill badge-danger"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">*location<span class="badge badge-pill badge-danger"></span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3">
        <h1 class="my-4" style="font-size:30px;">category tools:</h1>
        <div class="list-group">
          <a href="{% url 'catetory_detail' %}" class="list-group-item">stoika</a>
          <a href="{% url 'catetory_detail2' %}" class="list-group-item">formwork</a>
          <a href="{% url 'home' %}" class="list-group-item">all</a>
        </div>
        <div class="cart" >
          {% with total_items=cart|length %}
{% if cart|length > 0 %}
Your cart:
<a href="{% url 'cart:cart_detail' %}" class="list-group-item">
{{ total_items }} item{{ total_items|pluralize }},
${{ cart.get_total_price }}
</a>
{% else %}
Your cart is empty.
{% endif %}
{% endwith %}
        </div>
      </div>
      <!-- /.col-lg-3 -->

      

      

        

      

        {% block content %}
        
        
      {% endblock content %}
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->


  <!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script
src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script
src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script src="{% static 'js/scripts.js' %}"></script>
</body>

</html>

templates/cart_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
  <hr>
  <br>
  <br>
  <hr>
  <br>

    {% for item in cart %}
            {% with product=item.product %}
<div class="row">
    <div class="col-md-4">
        <img src="{{ product.image.url }}" alt="" class="img-fluid">
    </div>
    <div class="col-md-8">
        <h3>title: {{ product.name }}</h3>
        <p>price: {{ product.price }}</p>
        <p>quantity: {{ item.quantity }}</p>
        <p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ item.update_quantity_form.quantity }}
            {{ item.update_quantity_form.update }}
            <input type="submit" value="Update">
            {% csrf_token %}
            </form>
        </p>

        <p><a href="{% url 'cart:cart_remove' product.id%}" class="btn btn-primary">Remove</a></p>
        <p class="num">${{ item.total_price }}</p>

        <form action="{% url 'cart:cart_add' product.id %}" method="post">
          {{ cart_product_form }}
          {% csrf_token %}
          <input type="submit" value="Add to cart">
          </form>
        
        <hr>
    </div>
    {% endwith %}
{% endfor %}

        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'home' %}" class="btn btn-primary">Continue shopping</a>
        <a href="{% url 'orders:order_create' %}" class="btn btn-primary">
            Checkout
            </a>
    </p>

{% endblock %}

templates/cat_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="col-lg-9">
  <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <img class="d-block img-fluid" src="https://st3.depositphotos.com/10853016/18691/v/1600/depositphotos_186916394-stock-illustration-illustration-on-the-theme-of.jpg" style="height: 400px; width:2000px ;" >
      </div>
    </div>
  </div>



<div class="row">
  {% for prod in cat_prod %}
{% if prod.name == 'stoika' %}
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">         
          <a href="#"><img class="card-img-top" src="{{ prod.image.url }}" alt=""></a>
          <div class="card-body">
            <h4 class="card-title" style="color: rgb(91, 150, 150);">{{ prod.name }}</h4>
            <h5 style="color: rgb(145, 231, 46);" >{{ prod.price }} $</h5>
            <p class="card-text">{{ prod.description }}</p>
          </div>
        </div>
      </div>
{% endif %}
  {% endfor %}
</div>


<div class="row">
  {% for prod in cat_prod2 %}
{% if prod.name == 'formwork' %}
      <div class="col-lg-4 col-md-6 mb-4">
        <div class="card h-100">         
          <a href="#"><img class="card-img-top" src="{{ prod.image.url }}" alt=""></a>
          <div class="card-body">
            <h4 class="card-title" style="color: rgb(91, 150, 150);">{{ prod.name }}</h4>
            <h5 style="color: rgb(145, 231, 46);" >{{ prod.price }} $</h5>
            <p class="card-text">{{ prod.description }}</p>
          </div>
        </div>
      </div>
{% endif %}
  {% endfor %}
</div>


{% endblock %}

templates/create.html
{% block content %}
    <h1>Checkout</h1>
    <div class="order-info">
        <h3>Your order</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: ${{ cart.get_total_price }}</p>
    </div>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="Place order"></p>
        {% csrf_token %}
    </form>
{% endblock %}

templates/created.html
{% block content %}
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
        <strong>{{ order.id }}</strong>.</p>
        <a href="{% url 'home' %}" class="btn btn-primary">Continue shopping</a>
{% endblock %}

templates/formwork.html
<hr>
    <!-- <img src="https://cdn.peri.com/.imaging/l/dam/c13dd084-3779-4925-a1b9-484fcb537797/95507/trio-panel-formwork.jpg" class="img-fluid" alt="...">
    <hr>
    <img src="https://img.archiexpo.com.ru/images_ae/photo-g/3627-6661627.jpg" class="img-fluid" alt="...">
    <hr>
    <img src="https://image.made-in-china.com/2f0j00iocGQuDEITkN/Euro-Form-Hizen-Steel-Frame-Plywood-Concrete-Formwork.jpg" style="height: 500px;" alt="...">
    <hr>
    <img src="http://www.dzcsformwork.com/upload/201510121854223844745.JPG" style="height: 500px;" alt="...">

    <hr>




    <p>Характеристики: </p>
    

    <table class="table table-striped">
    <tbody>
      <tr>
        <td>Диоганаль</td>
        <td>#</td>
      </tr>
    <tr>
        <td>Дисплей</td>
        <td>#</td>
      </tr>
    <tr>
        <td>Процессор</td>
        <td>#</td>
      </tr>
    <tr>
        <td>Опретивная память</td>
        <td>#</td>
      </tr>
    <tr>
        <td>Видеокарта</td>
        <td>#</td>
      </tr>
    <tr>
        <td>Время работы</td>
        <td>#</td>
      </tr>
    </tbody>
  </table>

</div> -->


<hr>



<div class="card mb-3">
   
    <img src="https://cdn.peri.com/.imaging/l/dam/c13dd084-3779-4925-a1b9-484fcb537797/95507/trio-panel-formwork.jpg" style="height: 300px;" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">drill</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  <hr>
  <br>
    <img src="https://img.archiexpo.com.ru/images_ae/photo-g/3627-6661627.jpg"  style="height: 300px;" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">tools</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
<hr>
<br>
    <img src="https://image.made-in-china.com/2f0j00iocGQuDEITkN/Euro-Form-Hizen-Steel-Frame-Plywood-Concrete-Formwork.jpg" class="card-img-top" alt="..." style="height: 300px;">
    <div class="card-body">
      <h5 class="card-title">bump stop</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>

    <hr>
    <br>
        <img src="http://www.dzcsformwork.com/upload/201510121854223844745.JPG"  style="height: 300px;" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">compressor</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>


        <hr>
        <br>
            <img src="https://img.edilportale.com/product-thumbs/b_prodotti-49932-rel743c171e-ce81-4ae3-b1b9-428535e24c7f.jpg"  style="height: 300px;" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">concrete mixer</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>


            <hr>
            <br>
                <img src="https://prokatinstrumenta.kg/wp-content/uploads/2018/03/opalubki-korejskie3-600x800.jpeg"  style="height: 300px;" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">concrete mixer</h5>
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>


                <hr>
                <br>
                    <img src="https://i.ytimg.com/vi/uqg46gH7KW0/maxresdefault.jpg"  style="height: 300px;" class="card-img-top" alt="...">
                    <div class="card-body">
                      <h5 class="card-title">concrete mixer</h5>
                      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div>

                    <hr>
                    <br>
                        <img src="https://i.ytimg.com/vi/uqg46gH7KW0/maxresdefault.jpg"  style="height: 300px;" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h5 class="card-title">concrete mixer</h5>
                          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                        </div>


                        <hr>
                        <br>
                            <img src="https://image.made-in-china.com/202f0j10DOHQhqaSbWov/Construction-Formwork-Flat-Tie-Wedge-Pin.jpg"  style="height: 300px;" class="card-img-top" alt="...">
                            <div class="card-body">
                              <h5 class="card-title">concrete mixer</h5>
                              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                            </div>
    

                            <hr>
                            <br>
                                <img src="https://img5.lalafo.com/i/posters/original/c0/31/55/ef0715c41362b9ef6e7c597a88.jpeg"  style="height: 300px;" class="card-img-top" alt="...">
                                <div class="card-body">
                                  <h5 class="card-title">concrete mixer</h5>
                                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                                  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                                </div>

</div>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="col-lg-9">
  <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <img class="d-block img-fluid" src="https://st3.depositphotos.com/10853016/18691/v/1600/depositphotos_186916394-stock-illustration-illustration-on-the-theme-of.jpg" style="height: 400px; width:2000px ;" >
      </div>
    </div>
  </div>




  <div class="row">
    {% for prod in product %}
    
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100">
        <a class="portfolio-link" style="text-decoration: none;" data-toggle="modal" href="#productModal"  data-target="#productModal" data-url=""> 
        <img class="card-img-top" src="{{ prod.image.url }}" alt="">
      </a>
        <div class="card-body">
          <a href="{% url 'product_detail' prod.slug %}">
          <h4 class="card-title" style="color: rgb(91, 150, 150);">{{ prod.name }}</h4>
        </a>
          <h5 style="color: rgb(145, 231, 46);" >{{ prod.price }} $</h5>
          <p class="card-text">{{ prod.description }}</p>
        
        </div>
      </div>
    </div>

    {% endfor %}
</div>

<div class="modal fade" id="productModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
          <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
          <div class="modal-body">
              <div class="modal-product jq-product-wrapper"><!--jq-product-wrapper Полет товара в корзину без обновления страницы-->

              </div><!-- .modal-product -->
          </div><!-- .modal-body -->
      </div><!-- .modal-content -->
  </div><!-- .modal-dialog -->
</div>
<!-- END Modal -->



{% endblock content %}

templates/modal-product.html
{% load staticfiles %}

        <div class="product-images">
            <div class="main-image images">
                <img alt="#" src="{{ modal_product.image.url }}" width="450px" height="250"/>
            </div>
        </div><!-- .product-images -->
        <div class="product-info">
            <h1>{{ modal_product.name }}</h1>
            <div class="price-box-3">
                <hr />
                <div class="s-price-box">

                    <span class="old-price">{{ modal_product.price }} сом</span>
                </div>
                <hr />
            </div>

            </div>
            <div class="quick-desc">
                {{ modal_product.description }}
            </div>

            <div style="display: inline-block;">
                <div class="input-group">
                    
                    <button type="submit" class="btn btn-danger">Купить</button>

                </div>
            </div>

templates/payment_canceled.html
{% extends "base.html" %}
{% block content %}
<h1>Your payment has not been processed</h1>
<p>There was a problem processing your payment.</p>
{% endblock %}

templates/pdf.html
<html>
<body>
<h1>My Shop</h1>
<p>
Invoice no. {{ order.id }}
<br>
<span class="secondary">
{{ order.created|date:"M d, Y" }}
</span>
</p>
<h3>Bill to</h3>
<p>
{{ order.first_name }} {{ order.last_name }}<br>
{{ order.email }}<br>
{{ order.address }}<br>
{{ order.postal_code }}, {{ order.city }}
</p>
<h3>Items bought</h3>
<table>
<thead>
<tr>
<th>Product</th>
<th>Price</th>
<th>Quantity</th>
<th>Cost</th>
</tr>
</thead>
<tbody>
{% for item in order.items.all %}
<tr class="row{% cycle '1' '2' %}">
<td>{{ item.product.name }}</td>
<td class="num">${{ item.price }}</td>
<td class="num">{{ item.quantity }}</td>
<td class="num">${{ item.get_cost }}</td>
</tr>
{% endfor %}
<tr class="total">
<td colspan="3">Total</td>
<td class="num">${{ order.get_total_cost }}</td>
</tr>
</tbody>
</table>

{% if order == True%}
Paid
{% else %}
Pending payment
{% endif %}
</span>
</body>
</html>

templates/proccess.html
{% extends "base.html" %}
{% block title %}Pay by credit card{% endblock %}
{% block content %}
<h1>Pay by credit card</h1>
<form action="." id="payment" method="post">
<label for="card-number">Card Number</label>
<div id="card-number" class="field"></div>
<label for="cvv">CVV</label>
<div id="cvv" class="field"></div>
<label for="expiration-date">Expiration Date</label>
<div id="expiration-date" class="field"></div>
<input type="hidden" id="nonce" name="payment_method_nonce" value="">
{% csrf_token %}
<input type="submit" value="Pay">
</form>
<!—Подключаем клиента Braintree. -->
<script src="https://js.braintreegateway.com/web/3.29.0/js/client.min.js"></script>
<!—Подключаем компонент Hosted Fields. -->
<script src="https://js.braintreegateway.com/web/3.29.0/js/hosted-
fields.min.js"></script>
<script>
var form = document.querySelector('#payment');
var submit = document.querySelector('input[type="submit"]');
braintree.client.create({
authorization: '{{ client_token }}'
}, function (clientErr, clientInstance) {
if (clientErr) {
console.error(clientErr);
return;
}
braintree.hostedFields.create({
client: clientInstance,
styles: {
'input': {'font-size': '13px'},
'input.invalid': {'color': 'red'},
'input.valid': {'color': 'green'}
},
fields: {
number: {selector: '#card-number'},
cvv: {selector: '#cvv'},
expirationDate: {selector: '#expiration-date'}
}
}, function (hostedFieldsErr, hostedFieldsInstance) {
if (hostedFieldsErr) {
console.error(hostedFieldsErr);
return;
}
submit.removeAttribute('disabled');
form.addEventListener('submit', function (event) {
event.preventDefault();
hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
if (tokenizeErr) {
console.error(tokenizeErr);
return;
}
// Задаем значение поля для отправки токена на сервер.
document.getElementById('nonce').value = payload.nonce;
// Отправляем форму на сервер.
document.getElementById('payment').submit();
});
}, false);
});
});
</script>
{% endblock %}

templates/product_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="col-lg-9">
<nav aria-label="breadcrumb" class="mt-2">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="#">category</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
  </ol>
</nav>
<div class="row">
    <div class="col-md-4">
        <img src="{{ product.image.url }}" alt="" class="img-fluid">
    </div>
    <div class="col-md-8">
        <h3>{{ product.name }}</h3>
        <p>Цена: {{ product.price }}</p>
        <p>Описание: {{ product.description }}</p>
        <p>Телефон номер: </p>
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
          {{ cart_product_form }}
          {% csrf_token %}
          <input type="submit" value="Add to cart">
          </form>
        
        <hr>
    </div>
    {% if product.name == 'formwork' %}
        {% include 'formwork.html' %}
    {% elif product.name == 'scaffs' %}
        {% include 'scaffs.html' %}
    {% elif product.name == 'building tool' %}
        {% include 'tools.html' %}
    {% elif product.name == 'stoika' %}
        {% include 'stoika.html' %}
    {% endif %}
{% endblock content %}

templates/scaffs.html
{% load static %}


{% block content %}


<h1>english zone</h1>

{% endblock %}

templates/stoika.html
<hr>



<div class="card mb-3">
   
    <img src="https://ravchan.ru/wp-content/uploads/stojki-dlya-opalubki-700x525.jpg" style="height: 300px;" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">drill</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  <hr>
  <br>
    <img src="https://image.made-in-china.com/43f34j00BaNYmQdEbugn/High-Loading-Capacity-Steel-Props-for-Construction.jpg"  style="height: 300px;" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">tools</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
<hr>
<br>
    <img src="https://p-b-s.ru/wp-content/uploads/2018/10/%D1%82%D0%B5%D0%BB%D0%B5%D1%81%D0%BA%D0%BE%D0%BF%D1%8B.jpg" class="card-img-top" alt="..." style="height: 300px;">
    <div class="card-body">
      <h5 class="card-title">bump stop</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>

    <hr>
    <br>
        <img src="https://rsk-spb.com/upload/medialibrary/f7b/f7bbe412c7f51d9a0743263eb3cb7d3f.jpg"  style="height: 300px;" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">compressor</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>


        <hr>
        <br>
            <img src="https://img01.flagma.uz/photo/stoyka-teleskopicheskaya-domkrat-dlya-1719089_big.jpg"  style="height: 300px;" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">concrete mixer</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>

            

</div>